// Pedir lista de clientes
export const REQUEST_CLIENTE_LISTA = "REQUEST_CLIENTE_LISTA";
export const SUCCESS_CLIENTE_LISTA = "SUCCESS_CLIENTE_LISTA";
export const FAIL_CLIENTE_LISTA = "FAIL_CLIENTE_LISTA";
export const RESET_CLIENTE_LISTA = "RESET_CLIENTE_LISTA";

// Pedir lista de clientes venta
export const REQUEST_CLIENTE_VENTA_LISTA = "REQUEST_CLIENTE_VENTA_LISTA";
export const SUCCESS_CLIENTE_VENTA_LISTA = "SUCCESS_CLIENTE_VENTA_LISTA";
export const FAIL_CLIENTE_VENTA_LISTA = "FAIL_CLIENTE_VENTA_LISTA";
export const RESET_CLIENTE_VENTA_LISTA = "RESET_CLIENTE_VENTA_LISTA";

// Pedir un solo cliente
export const REQUEST_CLIENTE_DETALLES = "REQUEST_CLIENTE_DETALLES";
export const SUCCESS_CLIENTE_DETALLES = "SUCCESS_CLIENTE_DETALLES";
export const FAIL_CLIENTE_DETALLES = "FAIL_CLIENTE_DETALLES";
export const RESET_CLIENTE_DETALLES = "RESET_CLIENTE_DETALLES";

// Actualizar un cliente
export const REQUEST_CLIENTE_ACTUALIZAR = "REQUEST_CLIENTE_ACTUALIZAR";
export const SUCCESS_CLIENTE_ACTUALIZAR = "SUCCESS_CLIENTE_ACTUALIZAR";
export const FAIL_CLIENTE_ACTUALIZAR = "FAIL_CLIENTE_ACTUALIZAR";
export const RESET_CLIENTE_ACTUALIZAR = "RESET_CLIENTE_ACTUALIZAR";

// Registrar un nuevo cliente
export const REQUEST_CLIENTE_REGISTRAR = "REQUEST_CLIENTE_REGISTRAR";
export const SUCCESS_CLIENTE_REGISTRAR = "SUCCESS_CLIENTE_REGISTRAR";
export const FAIL_CLIENTE_REGISTRAR = "FAIL_CLIENTE_REGISTRAR";
export const RESET_CLIENTE_REGISTRAR = "RESET_CLIENTE_REGISTRAR";

// Borrar un cliente
export const REQUEST_CLIENTE_BORRAR = "REQUEST_CLIENTE_BORRAR";
export const SUCCESS_CLIENTE_BORRAR = "SUCCESS_CLIENTE_BORRAR";
export const FAIL_CLIENTE_BORRAR = "FAIL_CLIENTE_BORRAR";
export const RESET_CLIENTE_BORRAR = "RESET_CLIENTE_BORRAR";
