export const REQUEST_CUENTA_UPDATE = "REQUEST_CUENTA_UPDATE";
export const SUCCESS_CUENTA_UPDATE = "SUCCESS_CUENTA_UPDATE";
export const FAIL_CUENTA_UPDATE = "FAIL_CUENTA_UPDATE";
export const RESET_CUENTA_UPDATE = "RESET_CUENTA_UPDATE";
