export const REQUEST_CUENTA_DETALLES = "REQUEST_CUENTA_DETALLES";
export const SUCCESS_CUENTA_DETALLES = "SUCCESS_CUENTA_DETALLES";
export const FAIL_CUENTA_DETALLES = "FAIL_CUENTA_DETALLES";
export const RESET_CUENTA_DETALLES = "RESET_CUENTA_DETALLES";

export const REQUEST_CUENTA_UPDATE = "REQUEST_CUENTA_UPDATE";
export const SUCCESS_CUENTA_UPDATE = "SUCCESS_CUENTA_UPDATE";
export const FAIL_CUENTA_UPDATE = "FAIL_CUENTA_UPDATE";
export const RESET_CUENTA_UPDATE = "RESET_CUENTA_UPDATE";

export const REQUEST_CUENTA_DELETE = "REQUEST_CUENTA_DELETE";
export const SUCCESS_CUENTA_DELETE = "SUCCESS_CUENTA_DELETE";
export const FAIL_CUENTA_DELETE = "FAIL_CUENTA_DELETE";
