// Pedir lista de VENTAS
export const REQUEST_VENTA_LISTA = "REQUEST_VENTA_LISTA";
export const SUCCESS_VENTA_LISTA = "SUCCESS_VENTA_LISTA";
export const FAIL_VENTA_LISTA = "FAIL_VENTA_LISTA";
export const RESET_VENTA_LISTA = "RESET_VENTA_LISTA";

// Pedir lista de VENTAS para el reporte
export const REQUEST_VENTA_REPORTE_LISTA = "REQUEST_VENTA_REPORTE_LISTA";
export const SUCCESS_VENTA_REPORTE_LISTA = "SUCCESS_VENTA_REPORTE_LISTA";
export const FAIL_VENTA_REPORTE_LISTA = "FAIL_VENTA_REPORTE_LISTA";
export const RESET_VENTA_REPORTE_LISTA = "RESET_VENTA_REPORTE_LISTA";

// Pedir un solo VENTA
export const REQUEST_VENTA_DETALLES = "REQUEST_VENTA_DETALLES";
export const SUCCESS_VENTA_DETALLES = "SUCCESS_VENTA_DETALLES";
export const FAIL_VENTA_DETALLES = "FAIL_VENTA_DETALLES";
export const RESET_VENTA_DETALLES = "RESET_VENTA_DETALLES";

// Actualizar un VENTA
export const REQUEST_VENTA_ACTUALIZAR = "REQUEST_VENTA_ACTUALIZAR";
export const SUCCESS_VENTA_ACTUALIZAR = "SUCCESS_VENTA_ACTUALIZAR";
export const FAIL_VENTA_ACTUALIZAR = "FAIL_VENTA_ACTUALIZAR";
export const RESET_VENTA_ACTUALIZAR = "RESET_VENTA_ACTUALIZAR";

// Registrar un nuevo VENTA
export const REQUEST_VENTA_REGISTRAR = "REQUEST_VENTA_REGISTRAR";
export const SUCCESS_VENTA_REGISTRAR = "SUCCESS_VENTA_REGISTRAR";
export const FAIL_VENTA_REGISTRAR = "FAIL_VENTA_REGISTRAR";
export const RESET_VENTA_REGISTRAR = "RESET_VENTA_REGISTRAR";

// No es posible borrar una venta
